export const actions = {
  ASYNC_LOGIN: "ASYNC_LOGIN",
  ASYNC_REGISTER: "ASYNC_REGISTER",
  ASYNC_GET_USER: "ASYNC_GET_USER",
  CHANGE_USER_LOGGED: "CHANGE_USER_LOGGED",
  ASYNC_LOGOUT: "ASYNC_LOGOUT",
  ASYNC_CHECK_TRANSFER_IS_VALID: "ASYNC_CHECK_TRANSFER_IS_VALID",
  CHANGE_NEW_TRANSFER_ITEM: "CHANGE_NEW_TRANSFER_ITEM",
  CHANGE_TRANSFER_STATUS: "CHANGE_TRANSFER_STATUS",
  ASYNC_NEW_TRANSFER: "ASYNC_NEW_TRANSFER",
  ASYNC_GET_TRANSFERS: "ASYNC_GET_TRANSFERS",
  CHANGE_TRANSFERS: "CHANGE_TRANSFERS",
  FINISH_TRANSFER: "FINISH_TRANSFER",
  SET_LOADING_NEW_TRANSFER: "SET_LOADING_NEW_TRANSFER",
  SET_LOADING_GET_TRANSFER: "SET_LOADING_GET_TRANSFER",
  CHANGE_TRANSFER_FORM: "CHANGE_TRANSFER_FORM",
  SET_LOADING_GET_USER: "SET_LOADING_GET_USER",
  ASYNC_GET_CONTACTS: "ASYNC_GET_CONTACTS",
  SET_LOADING_GET_CONTACTS: "SET_LOADING_GET_CONTACTS",
  CHANGE_CONTACT_EMAIL: "CHANGE_CONTACT_EMAIL",
  ASYNC_ADD_CONTACT: "ASYNC_ADD_CONTACT",
  SET_LOADING_ADD_CONTACT: "SET_LOADING_ADD_CONTACT",
  ASYNC_REMOVE_CONTACT: "ASYNC_REMOVE_CONTACT",
  SET_LOADING_REMOVE_CONTACT: "SET_LOADING_REMOVE_CONTACT",

}

const BASEPATH = 'http://localhost:8000'

export const urls = {
  DO_LOGIN: `${BASEPATH}/account/login`,
  DO_REGISTER: `${BASEPATH}/account/register`,
  GET_USER_BY_EMAIL: `${BASEPATH}/account/email`,
  GET_USER: `${BASEPATH}/account`,
  TRANSFERS: `${BASEPATH}/transfer`,
}